### ISSUE TITLE
Error from ZxcvbnPhp library

### ISSUE THREAD

**Issue by Frenzie** [Spuds/Elk_Password_Entropy#3]
Exception: syntax error, unexpected token "match", expecting variable

sources/ext/ZxcvbnPhp/Matcher.php

---

Might be related to https://github.com/Spuds/Elk_Password_Entropy/pull/2 since I didn't do much of any testing.

**Comment by Spuds** [comment]
Probably so ... I'd imagine they have updated the library since the addon was released, I'll have to take a look and if so how much the API has changed.

**Comment by Spuds** [comment]
Looking at https://github.com/bjeavons/zxcvbn-php there are some php 8.x commits so its just going to be a matter of did the API change in any breaking way.

**Comment by Frenzie** [comment]
PS Not caused by #2.

**Comment by Spuds** [comment]
I updated to the new lib and things seem fine now in php8
